### ISSUE TITLE
Cannot have functions or parameters named 'type' in the documentation language

### ISSUE THREAD

**Issue by kartben** [SierraWireless/org.eclipse.koneki.ldt#3]
If you name a function or a parameter "type" in the documentation language, it is being ignored.

**Comment by KINFOO** [comment]
It is a limitation from our implementation.
"type" and the other tags are reserved keywords. The lexer handles them as keywords and not identifiers.
We have to sort this limitation out.

**Comment by sbernard31** [comment]
I opened a bug on eclipse : https://bugs.eclipse.org/bugs/show_bug.cgi?id=381707
