### ISSUE TITLE
[luadocumentor] With @usage several lines of code are not aligned

### ISSUE THREAD

**Issue by KINFOO** [SierraWireless/org.eclipse.koneki.ldt#5]
Writing following documentation

```
-- @usage local i 
-- local v
-- local h
```

Resulting display is 

```
local i
 local v
 local h
```

The shift on the first line have to be sorted out.

**Comment by sbernard31** [comment]
I opened an eclipse bug : https://bugs.eclipse.org/bugs/show_bug.cgi?id=381705
