### ISSUE TITLE
Variable completion not working near string concatenation operator

### ISSUE THREAD

**Issue by lbarthelemy** [SierraWireless/org.eclipse.koneki.ldt#6]
Example:

local foo = "bar"
local stuff = "stuff"..fo

When triggering variable completion after typing "..fo", nothing appears.
iIt seems the issue doesn't happen when variable to complete is before ".." operator.

Seen on
Developer Studio for ALEOS
Version : 1.0.0.201204261652

**Comment by sbernard31** [comment]
Thanks for report, It's a bug. 
if you add a space between '..' and fo it works.
I open a bug on the eclipse bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=381696
For the next issues you could find, could you please open the bug on bugzilla : https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Koneki;component=LuaTools

**Comment by kartben** [comment]
FWIW this is fixed in latest nightly build
