### ISSUE TITLE
feature: manual typing of vars while developping

### ISSUE THREAD

**Issue by lbarthelemy** [SierraWireless/org.eclipse.koneki.ldt#7]
could be useful to that one day so that this can of pattern can dealt with:

local file = assert(io.open("foobar", "w+"))
file:write("plop") -- no completion on file var.

I guess it would be hard to document assert in a way to say it returns the same type of object given as parameter...
So something like: 

local myfile = assert(io.open("foobar", "w+"))
--- myfile [file] 
myfile:write("plop") -- myfile is known as a file var.

**Comment by sbernard31** [comment]
Good idea, we keep it in mind (https://bugs.eclipse.org/bugs/show_bug.cgi?id=381671)
